# Graph-Enhanced LightRAG 配置文件

# 数据处理配置
data:
  raw_docs_dir: "data/raw_docs/"
  chunks_file: "data/chunks.json"
  chunk_size: 200  # 文本块大小（单词数）
  chunk_overlap: 50  # 文本块重叠大小

# 图构建配置
graph:
  similarity_threshold: 0.8  # 文本相似度边阈值
  entity_overlap_threshold: 0.3  # 实体重叠边阈值
  max_neighbors: 5  # 每个节点的最大邻居数
  save_path: "data/document_graph.pkl"
  # 孤立节点连接策略
  connect_isolated_nodes: true
  llm_bridge_model: "gpt-3.5-turbo"  # 用于生成主题关联的模型

# 嵌入配置
embedding:
  model_name: "sentence-transformers/all-mpnet-base-v2"  # 使用在线模型名称
  local_model_path: "./models/all-mpnet-base-v2"  # 本地模型路径
  cache_dir: "data/embeddings/"
  dimension: 768

# 图嵌入配置
gnn:
  model_type: "GAT"  # 可选: GAT, GraphSAGE, GCN
  hidden_dim: 256
  output_dim: 768  # 与原始嵌入维度相同
  num_layers: 2
  heads: 4  # GAT专用
  dropout: 0.2
  save_path: "data/gnn_model.pt"

# 检索配置
retrieval:
  index_path: "data/faiss_index/"
  top_k: 5  # 检索的文档数量
  use_graph_enhanced: true  # 是否使用图增强嵌入
  hybrid_weight: 0.7  # 原始嵌入与图嵌入的混合权重 (0-1)

# 生成配置
generation:
  model_name: "google/flan-t5-large"  # 生成模型
  max_length: 512
  num_beams: 4
  temperature: 0.7

# 评估配置
evaluation:
  metrics: ["rouge", "bertscore", "recall@k", "precision@k"]
  test_data: "data/test_questions.json"

# 实验配置
experiment:
  name: "GraphLightRAG"
  baseline_comparison: ["RAG", "LightRAG", "GraphLightRAG"]
  seed: 42
  log_dir: "logs/"

# 文档分割配置
splitter:
  chunk_size: 1000  # 每个文本块的大小
  chunk_overlap: 200  # 文本块之间的重叠大小