from setuptools import setup, find_packages

setup(
    name="grag",
    version="0.1.0",
    description="Graph-based RAG (Retrieval-Augmented Generation) system",
    author="GRAG Team",
    author_email="info@grag.ai",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.20.0",
        "tiktoken>=0.5.0",
        "networkx>=2.6.0",
        "nano-vectordb>=0.1.0",
        "tenacity>=8.0.0",
        "openai>=1.0.0",
        "aioboto3>=11.0.0",
        "aiohttp>=3.8.0",
        "ollama>=0.1.0",
        "pydantic>=1.9.0",
        "transformers>=4.20.0",
        "torch>=1.10.0",
    ],
    extras_require={
        "neo4j": ["neo4j>=5.0.0"],
        "oracle": ["oracledb>=1.0.0"],
        "docx": ["unstructured>=0.7.0"],
        "lmdeploy": ["lmdeploy>=0.1.0"],
        "graph": ["graspologic>=0.1.0"],
        "all": [
            "neo4j>=5.0.0",
            "oracledb>=1.0.0",
            "unstructured>=0.7.0",
            "lmdeploy>=0.1.0",
            "graspologic>=0.1.0",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
